[package]
name = "stm32f103c8_test"
version = "0.1.0"
edition = "2021"

# Define the binary target
[[bin]]
name = "test_out_stm32f103c8"
path = "src/main.rs"
test = false
bench = false

[dependencies]
# Change stm32f103c8 to your chip name, if necessary.
embassy-stm32 = { version = "0.6.0", path = "./embassy/embassy-stm32", features = [ "defmt", "stm32f303vc", "unstable-pac", "memory-x", "time-driver-any" ]  }
embassy-sync = { version = "0.8.0", path = "./embassy/embassy-sync", features = ["defmt"] }
embassy-executor = { version = "0.10.0", path = "./embassy/embassy-executor", features = ["platform-cortex-m", "executor-interrupt", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.1", path = "./embassy/embassy-time", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-futures = { version = "0.1.2", path = "./embassy/embassy-futures" }

defmt = "1.0.1"
defmt-rtt = "1.1.0"

cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
heapless = { version = "0.9.2", default-features = false }
nb = "1.1.0"
static_cell = "2.0.0"
critical-section = "1.1"
ssd1306="0.10.0"
embedded-graphics = "0.8"
embedded-hal-bus = "0.2"

[profile.dev]
opt-level = "s"

[profile.release]
debug = 2
