[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "info"

[target.thumbv7m-none-eabi]
rustflags = [
  "-C", "linker=arm-none-eabi-gcc",
#   "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "relocation-model=static",
]